CREATE DATABASE D_ROMAN;
GO

USE D_ROMAN;
GO


CREATE TABLE TIPO_USUARIO(
	IdTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	nomeDescricao VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE USUARIO(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL unique,
	Senha VARCHAR(100) NOT NULL,
	IdTipoUsuario tinyint foreign key references TIPO_USUARIO(IdTipoUsuario)
)

CREATE TABLE TEMAS(
	IdTema INT PRIMARY KEY IDENTITY,
	nomeTema VARCHAR(100) NOT NULL,
)


CREATE TABLE PROJETO(
	IdProjeto INT PRIMARY KEY IDENTITY,
	nomeProjeto VARCHAR(100) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES USUARIO (IdUsuario)
)

ALTER TABLE PROJETO
ADD  IdTema INT FOREIGN KEY REFERENCES  Temas (IdTema)
GO





drop table PROJETO
drop table TEMAS
drop table TIPO_USUARIO
drop table USUARIO